### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by stuartleeks** [sayedihashimi/riddlerps#9]
I've got a project that I'm thinking of using riddlerps in, but there's currently no license file for the project. Would you mind adding one? (Preferably something permissive ;-) )

**Comment by sayedihashimi** [comment]
I normally use apache v2,but am open to others. I'm not going to be in front of a computer for a few days. If u send a pr its quicker.

**Comment by stuartleeks** [comment]
I tend to go for MIT as I like the brevity :-)

**Comment by stuartleeks** [comment]
Closing as #10  is merged
